spring:
  application:
  name: restAPI-sping-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/restapi-sping-boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    propperties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

